
import libs += tgui%lib{tgui}
main_src =
images = file{*.jpg}

switch $config.tgui.backend
{
    case 'sfml'
    {
        main_src += cxx{main-sfml}
    }
    case 'sdl'
    {
        main_src += cxx{main-sfml}
    }
}

exe{many_differen_widgets}: many_differen_widgets/cxx{*} $main_src $images $libs
exe{scalable_login_screen}: scalable_login_screen/cxx{*} $main_src $images $libs