import intf_libs = tgui%lib{tgui}
import intf_libs += sfml-system%lib{sfml-system}
import intf_libs += sfml-graphics%lib{sfml-window}
import intf_libs += sfml-graphics%lib{sfml-graphics}
impl_libs = # Implementation dependencies.

# Public headers.
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{tgui-sfml}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
lib{tgui-sfml}: TGUI/{hxx cxx}{**} $impl_libs $intf_libs

# Build options.
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/TGUI/
src_pfx_src = [dir_path] $src_root/src/TGUI/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
                -DTGUI_HAS_BACKEND_SFML

{hbmia obja}{*}: cxx.poptions += -DTGUI_SFML_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DTGUI_SFML_SHARED_BUILD

# Export options.
lib{tgui-sfml}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" -DTGUI_HAS_BACKEND_SFML
  cxx.export.libs = $intf_libs
}

liba{tgui-sfml}: cxx.export.poptions += -DTGUI_SFML_STATIC
libs{tgui-sfml}: cxx.export.poptions += -DTGUI_SFML_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
  lib{tgui-sfml}: bin.lib.version = "-$version.project_id"
else
  lib{tgui-sfml}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
{hxx ixx txx}{*}: install = false
