./: exe{tgui-gui-builder} legal{license.txt} doc{README.md} manifest


intf_libs = # Interface dependencies.
import intf_libs += tgui%lib{tgui}
impl_libs = # Implementation dependencies.

exe{tgui-gui-builder}: include/hxx{**} src/{cxx hxx}{**} $impl_libs $intf_libs

# Build options.
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
    exe{tgui-gui-builder}: bin.lib.version = "-$version.project_id"
else
    exe{tgui-gui-builder}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
{hxx ixx txx}{*}: install = false
